version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: chamaweb-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_chamados2
      MYSQL_USER: chamaweb_user
      MYSQL_PASSWORD: senhaforte
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - chamaweb-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - db
    networks:
      - chamaweb-network

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    depends_on:
      - db
    networks:
      - chamaweb-network

  report-service:
    build: ./report-service
    container_name: report-service
    depends_on:
      - db
    networks:
      - chamaweb-network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - auth-service
      - ticket-service
      - report-service
    networks:
      - chamaweb-network

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - auth-service
      - ticket-service
      - report-service
    networks:
      - chamaweb-network

networks:
  chamaweb-network:
    driver: bridge
